"""Type stubs for the dbt_artifacts_rs Rust extension module."""

from typing import Any, Iterator

class JsonObj:
    """A Python-accessible wrapper around a parsed JSON value.

    JSON objects support attribute access, dict operations, and iteration.
    JSON arrays support indexing, iteration, len(), and containment.
    Primitives are returned as native Python types.
    """

    def __getattr__(self, name: str) -> Any: ...
    def __getitem__(self, key: str | int) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __contains__(self, key: Any) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def to_python(
        self,
    ) -> dict[str, Any] | list[Any] | str | int | float | bool | None: ...

def parse_manifest_json(json_str: str) -> JsonObj: ...
def parse_catalog_json(json_str: str) -> JsonObj: ...
def parse_run_results_json(json_str: str) -> JsonObj: ...
