# generated by datamodel-codegen:
#   filename:  catalog_latest.json

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field

from dbt_artifacts_parser.parsers.base import BaseParserModel


class Metadata(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    dbt_schema_version: str | None = None
    dbt_version: str | None = '1.9.0b2'
    generated_at: str | None = None
    invocation_id: str | None = None
    env: dict[str, str] | None = None


class Metadata1(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str
    schema_: str = Field(..., alias='schema')
    name: str
    database: str | None = None
    comment: str | None = None
    owner: str | None = None


class Columns(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    type: str
    index: int
    name: str
    comment: str | None = None


class Stats(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    id: str
    label: str
    value: bool | str | float | None = None
    include: bool
    description: str | None = None


class Nodes(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    metadata: Metadata1 = Field(..., title='TableMetadata')
    columns: dict[str, Columns]
    stats: dict[str, Stats]
    unique_id: str | None = None


class Sources(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    metadata: Metadata1 = Field(..., title='TableMetadata')
    columns: dict[str, Columns]
    stats: dict[str, Stats]
    unique_id: str | None = None


class CatalogLatest(BaseParserModel):
    model_config = ConfigDict(
        extra='allow',
    )
    metadata: Metadata = Field(..., title='CatalogMetadata')
    nodes: dict[str, Nodes]
    sources: dict[str, Sources]
    errors: list[str] | None = None
    field_compile_results: Any = Field(None, alias='_compile_results')
