name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  config-file:
    default: 'dbt-bouncer.yml'
    description: 'Location of the YML config file.'
    required: false
  github-actor:
    description: User associated with the `github-token` input.
    required: true
  github-token:
    description: GitHub token that has has read access to packages.
    required: true

runs:
  using: composite

  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github-actor }}
        password: ${{ inputs.github-token }}

    - name: Run dbt-bouncer
      shell: bash
      run: >
        docker run --rm \
          --volume "$GITHUB_WORKSPACE":/app \
          ghcr.io/godatadriven/dbt-bouncer:v0.9.4 \
          --config-file /app/${{ inputs.config-file }}
