name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  config-file:
    default: 'dbt-bouncer.yml'
    description: 'Location of the YML config file.'
    required: false
  send-pr-comment:
    default: 'true'
    description: |
      true: Send a comment to the GitHub PR with a list of failed checks.
      false: Do not send a comment.
    required: false
runs:
  using: composite

  steps:
    - name: Run dbt-bouncer
      env:
        GITHUB_REF: ${{ github.ref }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
      run: >
        docker run --rm \
          --volume "$GITHUB_WORKSPACE":/app \
          ghcr.io/godatadriven/dbt-bouncer:v0.13.0 \
          --config-file /app/${{ inputs.config-file }} \
          --send-pr-comment ${{ inputs.send-pr-comment }}
