name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  config-file:
    default: 'dbt-bouncer.yml'
    description: 'Location of the YML config file.'
    required: false
  output-file:
    default: ''
    description: 'Name of the json file where check metadata will be saved.'
    required: false
  send-pr-comment:
    default: 'true'
    description: |
      true: Send a comment to the GitHub PR with a list of failed checks.
      false: Do not send a comment.
    required: false
runs:
  using: composite

  steps:
    - name: Assemble `output-file` parameter
      id: assemble-output-file-param
      shell: bash
      run: >
        if [[ "${{ inputs.output-file }}" = "" ]]; then
          echo "output-file-param=" >> $GITHUB_OUTPUT
        else
          echo "output-file-param=--output-file /app/${{ inputs.output-file }}" >> $GITHUB_OUTPUT
        fi

    - name: Run dbt-bouncer
      id: run-dbt-bouncer
      shell: bash
      run: >
        docker run --rm \
          --env GITHUB_REF='${{ github.ref }}' \
          --env GITHUB_REPOSITORY='${{ github.repository }}' \
          --env GITHUB_RUN_ID='${{ github.run_id }}' \
          --env GITHUB_TOKEN='${{ github.token }}' \
          --volume "$GITHUB_WORKSPACE":/app \
          ghcr.io/godatadriven/dbt-bouncer:v0.19.4 \
          --config-file /app/${{ inputs.config-file }} \
          --create-pr-comment-file ${{ inputs.send-pr-comment }} \
          ${{ steps.assemble-output-file-param.outputs.output-file-param }}

    - name: Send PR comment
      if: always() && ${{ inputs.send-pr-comment }} == 'true' && ${{ steps.run-dbt-bouncer.outputs.exit_code != 0 }}
      shell: bash
      run: >
        gh pr comment ${{ github.pull_request.number }} \
          --repo ${{ github.repository }} \
          --body-file /app/github-comment.md
