name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  config-file:
    default: 'dbt-bouncer.yml'
    description: 'Location of the YML config file.'
    required: false

runs:
  using: 'composite'

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          update-environment: false

    - name: Run dbt-bouncer
      shell: bash
      run: |
        wget https://github.com/godatadriven/dbt-bouncer/releases/download/v0.7.0/dbt-bouncer.pex -O ${{ github.action_path }}/dist/dbt-bouncer.pex
        ${{ github.action_path }}/dist/dbt-bouncer.pex  --config-file ${{ inputs.config-file }}
