name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  config-file:
    default: 'dbt-bouncer.yml'
    description: 'Location of the YML config file.'
    required: false

runs:
  using: composite

  steps:
    - name: Run dbt-bouncer
      shell: bash
      run: >
        docker run --rm \
          --volume "$GITHUB_WORKSPACE":/app \
          ghcr.io/godatadriven/dbt-bouncer:v0.9.0 \
          --config-file /app/${{ inputs.config-file }}
