name: 'dbt-bouncer'
description: 'Configure and enforce conventions for your dbt project.'
inputs:
  dbt-artifacts-dir:
    default: '.'
    description: 'Directory where the dbt artifacts exists, generally the `target` directory inside a dbt project.'
    required: false

runs:
  using: 'composite'

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          update-environment: false

    - name: Run dbt-bouncer
      shell: bash
      run: |
        ${{ github.action_path }}/dist/dbt-bouncer.pex \
          --dbt-artifacts-dir ${{ inputs.dbt-artifacts-dir }}
