edit_uri: docs/
repo_name: godatadriven/dbt-bouncer
repo_url: https://github.com/godatadriven/dbt-bouncer
site_name: dbt-bouncer
site_url: https://godatadriven.github.io/dbt-bouncer/

extra:
  version:
    alias: true
    canonical_version: stable
    default: stable
    provider: mike

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Config File: config_file.md
  - Checks:
    - Checks: checks/index.md
    - Catalog:
      - Catalog Sources: checks/catalog/check_catalog_sources.md
      - Columns: checks/catalog/check_columns.md
    - Manifest:
      - Exposures: checks/manifest/check_exposures.md
      - Lineage: checks/manifest/check_lineage.md
      - Macros: checks/manifest/check_macros.md
      - Metadata: checks/manifest/check_metadata.md
      - Models: checks/manifest/check_models.md
      - Sources: checks/manifest/check_sources.md
      - Semantic Models: checks/manifest/check_semantic_models.md
      - Unit Tests: checks/manifest/check_unit_tests.md
    - Run Results:
      - Run Results: checks/run_results/check_run_results.md
  - FAQ: faq.md
  - CLI: cli.md
  - Contributing: CONTRIBUTING.md

plugins:
  - git-revision-date-localized
  - mkdocstrings:
      custom_templates: docs/templates
      handlers:
        python:
          paths:
            - src/dbt_bouncer/checks
          options:
            docstring_style: google
            filters: ["check_"]
            group_by_category: true
            heading_level: 1
            inherited_members: true
            members_order: source
            show_bases: false
            show_docstring_classes: false
            show_docstring_raises: false
            show_if_no_docstring: true
            show_root_toc_entry: false
            show_source: true
            show_signature: false
            show_submodules: true
            summary: true
  - search

theme:
  custom_dir: docs/overrides
  favicon: assets/logo.svg
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate
  icon:
    edit: material/pencil
    repo: fontawesome/brands/github
    view: material/eye
  logo: assets/logo.svg
  name: material
  palette:
    primary: custom
