name: 'dbt_bouncer_test_project'
version: '1.0.0'
config-version: 2

profile: 'dbt_bouncer'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_bouncer_test_project:
    intermediate:
      access: protected
      schema: intermediate
    marts:
      access: public
      schema: marts
    staging:
      access: protected
      crm:
        schema: stg_crm
        tags:
            - crm
      payments:
        schema: stg_payments
