name: 🐛 Bug
description: Report a bug or an issue you've found with `dbt-bouncer
title: "[Bug] <title>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config file...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please capture debug logs via `LOG_LEVEL=DEBUG dbt-bouncer ...` and paste them here.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Python**: 3.10.5 (`python3 --version`)
          - **dbt-bouncer**: X.X.X (`dbt-bouncer --version`)
      value: |
        - OS:
        - Python:
        - dbt-bouncer:
      render: markdown
    validations:
      required: false
  - type: input
    attributes:
      label: Add your company's website here to be added to our list of [users](https://godatadriven.github.io/dbt-bouncer/stable/users/#users).
      description: Do you use `dbt-bouncer` in your workplace?
    validations:
      required: false
