"""Generate the rule codes reference page from the check classes themselves.

The page is written to ``docs/checks/rule_codes.md``. Rule codes are declared via
the ``@check(code=...)`` decorator rather than in docstrings, so mkdocstrings
cannot render them — this script closes that gap and keeps the published mapping
in lockstep with the code.

Also acts as a consistency guard: it fails if a check has no rule code, or if a
code declared in ``dbt_bouncer.enums`` is not claimed by any check.
"""

from __future__ import annotations

import logging
import typing
from pathlib import Path

from dbt_bouncer.reporting.logger import configure_console_logging

DOC_PATH = Path("docs/checks/rule_codes.md")

# Human-readable label per rule code enum, keyed by the enum class name. Keeping
# this explicit avoids inferring prose from class names.
_GROUP_LABELS = {
    "CatalogRuleCode": "Catalog",
    "ExposureRuleCode": "Exposures",
    "LineageRuleCode": "Lineage",
    "MacroRuleCode": "Macros",
    "MetadataRuleCode": "Metadata",
    "ModelRuleCode": "Models",
    "RunResultsRuleCode": "Run results",
    "SeedRuleCode": "Seeds",
    "SemanticModelRuleCode": "Semantic models",
    "SnapshotRuleCode": "Snapshots",
    "SourceRuleCode": "Sources",
    "TestRuleCode": "Tests",
    "UnitTestRuleCode": "Unit tests",
}


def _escape(text: str) -> str:
    """Escape characters that would break a Markdown table cell.

    Args:
        text: The raw text.

    Returns:
        str: The escaped text.

    """
    return text.replace("|", "\\|")


def _summary(check_class: type) -> str:
    """Return the first line of a check's docstring.

    Args:
        check_class: The check class to summarise.

    Returns:
        str: The summary line, or an empty string if undocumented.

    """
    docstring = (check_class.__doc__ or "").strip()
    return docstring.splitlines()[0] if docstring else ""


def _yaml_name(check_class: type) -> str:
    """Return the snake_case name a check is referenced by in YAML config.

    Args:
        check_class: The check class to inspect.

    Returns:
        str: The ``name`` Literal value, falling back to the class name.

    """
    name_field = check_class.model_fields.get("name")  # type: ignore[attr-defined]
    args = typing.get_args(name_field.annotation) if name_field else ()
    return args[0] if args else getattr(check_class, "__name__", "")


def _rule_code_enums() -> list[type]:
    """Return the rule code enums that make up the ``RuleCode`` union.

    Returns:
        list[type]: The enum classes, ordered by their prefix.

    """
    from dbt_bouncer.enums import RuleCode

    enums = list(typing.get_args(RuleCode))
    return sorted(enums, key=lambda e: next(iter(e))[:2])


def main() -> None:
    """Build the rule codes reference page.

    Raises:
        SystemExit: If a check has no rule code, or a declared code is unused.

    """
    configure_console_logging(0)

    # Import all check modules so every check class is registered.
    import dbt_bouncer.checks.catalog  # noqa: F401
    import dbt_bouncer.checks.manifest  # noqa: F401
    import dbt_bouncer.checks.run_results  # noqa: F401
    from dbt_bouncer.cli.list.utils import category_key
    from dbt_bouncer.enums import CheckCategory
    from dbt_bouncer.utils import get_check_objects

    logging.info("Collecting checks...")
    checks_by_code: dict[str, type] = {}
    uncoded: list[str] = []
    for check_class in get_check_objects():
        code = getattr(check_class, "code", None)
        if code is None:
            uncoded.append(check_class.__name__)
            continue
        checks_by_code[str(code)] = check_class

    if uncoded:
        msg = (
            f"{len(uncoded)} check(s) have no rule code: {', '.join(sorted(uncoded))}. "
            "Assign one via `@check(code=...)` and add it to `dbt_bouncer.enums`."
        )
        raise SystemExit(msg)

    # Map the module path segment used by check discovery back to the config key
    # users actually write in dbt-bouncer.yml.
    category_values = {c.directory: c.value for c in CheckCategory}

    # Derive the worked example from the real data — hardcoding a code here would
    # be the exact drift this page exists to prevent.
    code_by_name = {_yaml_name(cls): code for code, cls in checks_by_code.items()}
    example_name = "check_model_description_populated"
    if example_name not in code_by_name:
        example_name = sorted(code_by_name)[0]
    example_code = code_by_name[example_name]

    logging.info("Rendering %s...", DOC_PATH)
    lines: list[str] = [
        "<!-- Generated by scripts/generate_rule_codes_doc.py. Do not edit by hand. -->",
        "",
        "# Rule codes",
        "",
        "Every built-in check has a unique rule code: a two-letter prefix identifying the group of resources it applies to, followed by a three-digit number. Codes are stable — once published, a code always refers to the same check.",
        "",
        "## Referencing a check by its code",
        "",
        "Anywhere a check is named you may use its code instead. These two config entries are equivalent:",
        "",
        "```yaml",
        "manifest_checks:",
        f"  - name: {example_name}",
        f"  - code: {example_code}",
        "```",
        "",
        "Codes are also accepted in the `skip_checks` meta key on a dbt resource:",
        "",
        "```yaml",
        "models:",
        "  - name: my_model",
        "    meta:",
        "      skip_checks:",
        f"        - {example_code}",
        "```",
        "",
        "To browse codes from the command line, use [`dbt-bouncer list`](../cli.md), optionally filtered with `--group`:",
        "",
        "```shell",
        "dbt-bouncer list --group manifest_checks",
        "```",
        "",
        "## Prefixes",
        "",
        "| Prefix | Group | Config category | Checks |",
        "| --- | --- | --- | --- |",
    ]

    enums = _rule_code_enums()
    orphans: list[str] = []
    for enum_cls in enums:
        codes = sorted(str(member) for member in enum_cls)
        prefix = codes[0][:2]
        label = _GROUP_LABELS.get(enum_cls.__name__, enum_cls.__name__)
        # Every code in a group shares a config category, so the first is enough.
        known = [c for c in codes if c in checks_by_code]
        orphans.extend(c for c in codes if c not in checks_by_code)
        category = (
            category_values.get(category_key(checks_by_code[known[0]]), "")
            if known
            else ""
        )
        lines.append(f"| `{prefix}` | {label} | `{category}` | {len(codes)} |")

    if orphans:
        msg = (
            f"{len(orphans)} rule code(s) are declared in `dbt_bouncer.enums` but not "
            f"used by any check: {', '.join(sorted(orphans))}."
        )
        raise SystemExit(msg)

    for enum_cls in enums:
        codes = sorted(str(member) for member in enum_cls)
        label = _GROUP_LABELS.get(enum_cls.__name__, enum_cls.__name__)
        lines.extend(
            [
                "",
                f"## {label} (`{codes[0][:2]}`)",
                "",
                "| Code | Check | Description |",
                "| --- | --- | --- |",
            ]
        )
        for code in codes:
            check_class = checks_by_code[code]
            lines.append(
                f"| `{code}` | `{_yaml_name(check_class)}` | {_escape(_summary(check_class))} |"
            )

    DOC_PATH.write_text("\n".join(lines) + "\n")
    logging.info("Wrote %s checks to %s", len(checks_by_code), DOC_PATH)


if __name__ == "__main__":
    main()
