"""Utility functions for the init CLI subcommand."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, NamedTuple

from dbt_bouncer.enums import ConfigFileName

if TYPE_CHECKING:
    from dbt_bouncer.enums import PresetName


class InitConfig(NamedTuple):
    """Result of building an initial dbt-bouncer configuration."""

    config: dict[str, Any]
    checks_count: int


def build_initial_config(
    artifacts_dir: str,
    check_descriptions: bool,
    check_unique_tests: bool,
    check_naming: bool,
) -> InitConfig:
    """Build the configuration dictionary based on user's answers.

    Args:
        artifacts_dir: The directory where dbt artifacts are located.
        check_descriptions: Whether to check for model descriptions.
        check_unique_tests: Whether to check for unique tests on models.
        check_naming: Whether to check naming conventions for staging models.

    Returns:
        InitConfig: A named tuple with the configuration dictionary and the number of checks added.

    """
    manifest_checks = []

    if check_descriptions:
        manifest_checks.append(
            {
                "name": "check_model_description_populated",
                "description": "All models must have a description.",
            }
        )

    if check_unique_tests:
        manifest_checks.append(
            {
                "name": "check_model_has_unique_test",
                "description": "All models must have a unique test defined.",
            }
        )

    if check_naming:
        manifest_checks.append(
            {
                "name": "check_model_names",
                "description": "Models in the staging layer should always start with 'stg_'.",
                "include": "^models/staging",
                "model_name_pattern": "^stg_",
            }
        )

    config_dict = {
        "dbt_artifacts_dir": artifacts_dir,
        "manifest_checks": manifest_checks,
    }

    return InitConfig(config=config_dict, checks_count=len(manifest_checks))


def count_preset_checks(preset: PresetName) -> int:
    """Count the checks defined in a bundled preset.

    Args:
        preset: The preset name (minimal, standard, strict).

    Returns:
        int: The total number of checks across all categories.

    """
    from dbt_bouncer.presets import load_preset_contents

    contents = load_preset_contents(preset)
    return sum(
        len(v)
        for k, v in contents.items()
        if k.endswith("_checks") and isinstance(v, list)
    )


def write_preset_config_file(preset: PresetName) -> Path:
    """Write a bundled preset to `dbt-bouncer.yml`, comments preserved.

    Args:
        preset: The preset name (minimal, standard, strict).

    Returns:
        Path: The path to the created config file.

    """
    from dbt_bouncer.presets import read_preset_text

    config_path = Path(ConfigFileName.DBT_BOUNCER_YML)
    config_path.write_text(read_preset_text(preset), encoding="utf-8")
    return config_path


def write_config_file(config_dict: dict[str, Any]) -> Path:
    """Write the configuration dictionary to a file.

    Args:
        config_dict: The configuration dictionary to write.

    Returns:
        Path: The path to the created config file.

    """
    import yaml

    dumper: type[yaml.SafeDumper] = (
        yaml.CSafeDumper if hasattr(yaml, "CSafeDumper") else yaml.SafeDumper
    )
    config_path = Path(ConfigFileName.DBT_BOUNCER_YML)

    with config_path.open("w", encoding="utf-8") as f:
        f.write("# dbt-bouncer configuration\n# Generated by: dbt-bouncer init\n\n")
        yaml.dump(
            config_dict,
            f,
            default_flow_style=False,
            sort_keys=False,
            Dumper=dumper,
        )
    return config_path
