# [Optional] Directory where the dbt artifacts exists, generally the `target` directory inside a dbt project. Defaults to `$DBT_PROJECT_DIR/target` if $DBT_PROJECT_DIR is set, else `./target`.
dbt_artifacts_dir = "dbt_project/target"

[[catalog_checks]]
name = "check_column_description_populated"
include = "^models/marts"

[[catalog_checks]]
name = "check_column_name_complies_to_column_type"
column_name_pattern = "^is_.*"
exclude = "^models/staging"
types = ["BOOLEAN"]

[[catalog_checks]]
name = "check_column_name_complies_to_column_type"
column_name_pattern = ".*_date$"
include = "^models/staging"
types = ["DATE"]

[[catalog_checks]]
name = "check_column_name_complies_to_column_type"
column_name_pattern = "^[a-z_]*$"
types = ["BIGINT", "BOOLEAN", "DATE", "DOUBLE", "INTEGER", "VARCHAR"]

[[catalog_checks]]
name = "check_column_name_complies_to_column_type"
column_name_pattern = "^[a-z_]*$"
type_pattern = "^(?!STRUCT)"

[[catalog_checks]]
name = "check_column_names"
column_name_pattern = "[a-z_]*"

[[catalog_checks]]
name = "check_column_has_specified_test"
column_name_pattern = "^is_.*"
test_name = "not_null"

[[catalog_checks]]
name = "check_columns_are_all_documented"
include = "^models/marts"

[[catalog_checks]]
name = "check_columns_are_documented_in_public_models"

[[catalog_checks]]
name = "check_seed_columns_are_all_documented"

[[catalog_checks]]
name = "check_source_columns_are_all_documented"
exclude = "^models/staging/crm"

# Manifest checks: Exposures

[[manifest_checks]]
name = "check_exposure_based_on_model"

[[manifest_checks]]
name = "check_exposure_based_on_non_public_models"

[[manifest_checks]]
name = "check_exposure_based_on_view"

# Manifest checks: Lineage

[[manifest_checks]]
name = "check_lineage_permitted_upstream_models"
include = "^models/staging"
upstream_path_pattern = "$^"

[[manifest_checks]]
name = "check_lineage_permitted_upstream_models"
include = "^models/intermediate"
upstream_path_pattern = "^models/staging|^models/intermediate"

[[manifest_checks]]
name = "check_lineage_permitted_upstream_models"
include = "^models/marts"
upstream_path_pattern = "^models/staging|^models/intermediate"

[[manifest_checks]]
name = "check_lineage_seed_cannot_be_used"
include = "^models/intermediate|^models/marts"

[[manifest_checks]]
name = "check_lineage_source_cannot_be_used"
include = "^models/intermediate|^models/marts"

# Manifest checks: Macros

[[manifest_checks]]
name = "check_macro_arguments_description_populated"

[[manifest_checks]]
name = "check_macro_code_does_not_contain_regexp_pattern"
regexp_pattern = ".*[i][f][n][u][l][l].*"

[[manifest_checks]]
name = "check_macro_description_populated"

[[manifest_checks]]
name = "check_macro_max_number_of_lines"

[[manifest_checks]]
name = "check_macro_name_matches_file_name"

[[manifest_checks]]
name = "check_macro_property_file_location"

# Manifest checks: Metadata

[[manifest_checks]]
name = "check_project_name"
project_name_pattern = "^dbt_bouncer_"

# Manifest checks: Models

[[manifest_checks]]
name = "check_model_access"
include = "^models/intermediate"
access = "protected"
severity = "warn"

[[manifest_checks]]
name = "check_model_access"
include = "^models/marts"
access = "public"

[[manifest_checks]]
name = "check_model_access"
include = "^models/staging"
access = "protected"

[[manifest_checks]]
name = "check_model_code_does_not_contain_regexp_pattern"
regexp_pattern = ".*[i][f][n][u][l][l].*"

[[manifest_checks]]
name = "check_model_columns_have_relationship_tests"
column_name_pattern = "_fk$"

[[manifest_checks]]
name = "check_model_columns_have_meta_keys"
include = "^models/marts"
keys = ["maturity"]

[[manifest_checks]]
name = "check_model_columns_have_types"
include = "^models/marts"

[[manifest_checks]]
name = "check_model_contract_enforced_for_public_model"

[[manifest_checks]]
name = "check_model_depends_on_macros"
description = "Incremental models must use the `is_incremental` macro."
required_macros = ["dbt.is_incremental"]
materialization = "incremental"

[[manifest_checks]]
name = "check_model_depends_on_multiple_sources"

[[manifest_checks]]
name = "check_model_description_contains_regex_pattern"
include = "^models/marts/finance/customers"
regexp_pattern = ".*as well as some derived facts.*"

[[manifest_checks]]
name = "check_model_description_populated"

[[manifest_checks]]
name = "check_model_directories"
include = "^models"
permitted_sub_directories = ["intermediate", "marts", "staging", "utilities"]

[[manifest_checks]]
name = "check_model_directories"
include = "^models/staging"
permitted_sub_directories = ["crm", "payments"]

[[manifest_checks]]
name = "check_model_documentation_coverage"
min_model_documentation_coverage_pct = 90

[[manifest_checks]]
name = "check_model_documented_in_same_directory"

[[manifest_checks]]
name = "check_model_file_name"
include = "^models/marts"
file_name_pattern = ".*(s|v[0-9])\\.sql$"

[[manifest_checks]]
name = "check_model_grant_privilege"
include = "^models/marts"
privilege_pattern = "^select|^write"

[[manifest_checks]]
name = "check_model_grant_privilege_required"
include = "^models/marts"
privilege = "select"

[[manifest_checks]]
name = "check_model_hard_coded_references"

[[manifest_checks]]
name = "check_model_has_constraints"
include = "^models/marts"
required_constraint_types = ["primary_key"]

[[manifest_checks]]
name = "check_model_has_contracts_enforced"
include = "^models/marts"

[[manifest_checks]]
name = "check_model_has_exposure"
include = "^models/marts/finance"
exclude = "^models/marts/finance/customers_v[12].sql"

[[manifest_checks]]
name = "check_model_has_meta_keys"
keys = ["maturity"]

[[manifest_checks]]
name = "check_model_has_no_upstream_dependencies"
include = "^((?!int_*).)*$"
exclude = "^models/utilities/time_spines"

[[manifest_checks]]
name = "check_model_has_semi_colon"

[[manifest_checks]]
name = "check_model_has_tags"
include = "^models/staging/crm"
tags = ["crm"]

[[manifest_checks]]
name = "check_model_has_unique_test"

[[manifest_checks]]
name = "check_model_max_chained_views"

[[manifest_checks]]
name = "check_model_max_fanout"
max_downstream_models = 5

[[manifest_checks]]
name = "check_model_max_number_of_lines"

[[manifest_checks]]
name = "check_model_max_upstream_dependencies"

[[manifest_checks]]
name = "check_model_number_of_grants"
include = "^models/marts"
max_number_of_privileges = 2
min_number_of_privileges = 1

[[manifest_checks]]
name = "check_model_has_unit_tests"
include = "^models/marts"

[[manifest_checks]]
name = "check_model_names"
include = "^models/intermediate"
model_name_pattern = "^int_"

[[manifest_checks]]
name = "check_model_names"
description = "Models in the staging layer should always start with \"stg_\"."
include = "^models/staging"
model_name_pattern = "^stg_"

[[manifest_checks]]
name = "check_model_test_coverage"

[[manifest_checks]]
name = "check_model_property_file_location"

[[manifest_checks]]
name = "check_model_schema_name"
include = "^models/intermediate"
schema_name_pattern = ".*intermediate"

[[manifest_checks]]
name = "check_model_schema_name"
include = "^models/staging"
schema_name_pattern = ".*stg_.*"

[[manifest_checks]]
name = "check_model_names"
description = "Most model checks include the ability to filter by materialization, this is an example of how this is done."
include = "^models/intermediate"
materialization = "ephemeral"
model_name_pattern = "^int_"

# Manifest checks: Seeds

[[manifest_checks]]
name = "check_seed_column_names"
seed_column_name_pattern = "^[a-z_]*$"

[[manifest_checks]]
name = "check_seed_columns_have_types"

[[manifest_checks]]
name = "check_seed_description_populated"

[[manifest_checks]]
name = "check_seed_names"
include = "^seeds"
seed_name_pattern = "^raw_"

# Manifest checks: Semantic models

[[manifest_checks]]
name = "check_semantic_model_based_on_non_public_models"

# Manifest checks: Snapshots

[[manifest_checks]]
name = "check_snapshot_description_populated"

[[manifest_checks]]
name = "check_snapshot_has_tags"
exclude = "snapshots/snapshot_orders.sql"
tags = ["payment"]

[[manifest_checks]]
name = "check_snapshot_names"
include = "snapshots/snapshot_orders.sql"
snapshot_name_pattern = "^snapshot_"

# Manifest checks: Sources

[[manifest_checks]]
name = "check_source_description_populated"
min_description_length = 25

[[manifest_checks]]
name = "check_source_freshness_populated"

[[manifest_checks]]
name = "check_source_loader_populated"

[[manifest_checks]]
name = "check_source_has_meta_keys"
keys = [{ contact = ["email", "slack"] }, "owner"]

[[manifest_checks]]
name = "check_source_has_tags"
tags = ["example_tag"]

[[manifest_checks]]
name = "check_source_names"
source_name_pattern = "^[a-z0-9_]*$"

[[manifest_checks]]
name = "check_source_not_orphaned"
include = "^models/staging/crm"

[[manifest_checks]]
name = "check_source_property_file_location"

[[manifest_checks]]
name = "check_source_used_by_models_in_same_directory"

[[manifest_checks]]
name = "check_source_used_by_only_one_model"

# Manifest checks: Tests

[[manifest_checks]]
name = "check_test_has_meta_keys"
include = "^tests/"
keys = ["owner"]

[[manifest_checks]]
name = "check_test_has_tags"
include = "^models/marts"
tags = ["critical"]

# Manifest checks: Unit tests

[[manifest_checks]]
name = "check_unit_test_coverage"
include = "^models/marts"

[[manifest_checks]]
name = "check_unit_test_expect_format"

[[manifest_checks]]
name = "check_unit_test_given_formats"

# Manifest checks: Versions

[[manifest_checks]]
name = "check_model_latest_version_specified"
exclude = "^models/marts/finance/orders.sql"
include = "^models/marts"

[[manifest_checks]]
name = "check_model_version_allowed"
include = "^models/marts"
version_pattern = "[0-9]\\d*"

[[manifest_checks]]
name = "check_model_version_pinned_in_ref"
include = "^models/marts"

# Run results checks

[[run_results_checks]]
name = "check_run_results_max_execution_time"
include = "^models/staging"
exclude = "^models/staging/crm"
max_execution_time_seconds = 10
