---
name: pre-commit autoupdate

on:
    schedule:
        - cron: "0 9 1 * *" # 1st of each month at 09:00 UTC
    workflow_dispatch: {}

permissions:
    contents: write
    pull-requests: write

jobs:
    autoupdate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

            - name: Setup Python
              uses: ./.github/actions/setup_python_env
              with:
                install-python-deps: 'false'

            - run: pip install pre-commit

            - run: pre-commit autoupdate

            - name: Check for changes
              id: diff
              run: |
                  git diff --exit-code && echo "changed=false" >> "$GITHUB_OUTPUT" || echo "changed=true" >> "$GITHUB_OUTPUT"

            - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
              if: steps.diff.outputs.changed == 'true'
              with:
                  branch: build/pre-commit-autoupdate
                  commit-message: "build: pre-commit autoupdate"
                  delete-branch: true
                  labels: dependencies
                  title: "build: pre-commit autoupdate"
                  body: |
                      Automated pre-commit hook version updates via `pre-commit autoupdate`.
