---
  name: Release pipeline

  on:
      workflow_dispatch:
          inputs:
              version_bump_type:
                  description: The version bump type to perform.
                  required: true
                  type: choice
                  options:
                      - major
                      - minor
                      - patch
                      - stable
                      - alpha
                      - beta
                      - rc
                      - rc-major
                      - rc-minor
                      - rc-patch
                      - post
                      - dev

  env:
    IMAGE_NAME: ${{ github.repository }}
    REGISTRY: ghcr.io

  jobs:
      build-and-push-image:
          environment:
              name: publish
              url: https://pypi.org/p/dbt-bouncer
          runs-on: ubuntu-24.04
          permissions:
              contents: write
              id-token: write
              packages: write
          steps:
              - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

              - name: Fetch tags
                run: git fetch --prune --unshallow --tags

              - name: Setup Python
                id: setup-python
                uses: ./.github/actions/setup_python_env
                with:
                  install-python-deps: 'false'

              - name: Set latest version
                run: uv version $(git tag --sort version:refname | tail -n 1)

              - name: Bump version
                if: ${{ inputs.version_bump_type != 'rc-major' && inputs.version_bump_type != 'rc-minor' && inputs.version_bump_type != 'rc-patch' }}
                run: uv version --bump ${{ inputs.version_bump_type }}

              - name: Bump version (release candidate - major)
                if: ${{ inputs.version_bump_type == 'rc-major' }}
                run: uv version --bump major --bump rc

              - name: Bump version (release candidate - minor)
                if: ${{ inputs.version_bump_type == 'rc-minor' }}
                run: uv version --bump minor --bump rc

              - name: Bump version (release candidate - patch)
                if: ${{ inputs.version_bump_type == 'rc-patch' }}
                run: uv version --bump patch --bump rc

              - name: Update version in codebase
                run: uv run ./scripts/version_update.py --new-version $(uv version --short)

              # Need to re-install dbt-bouncer so version bump is visible when `dbt-bouncer --version` is called
              - name: Re-install dbt-bouncer
                run: make install

              - name: Save version to env var
                id: version
                run: |
                  echo "version=$(uv version --short)" >> $GITHUB_OUTPUT
                  echo "major=$(echo $(uv version --short | cut -d '.' -f 1))" >> $GITHUB_OUTPUT
                  echo "minor=$(echo $(uv version --short | cut -d '.' -f 2))" >> $GITHUB_OUTPUT
                  echo "patch=$(echo $(uv version --short | cut -d '.' -f 3))" >> $GITHUB_OUTPUT

              - name: Determine if prerelease flag is necessary
                run: |
                    [ "${{ inputs.version_bump_type }}" = "rc" ] || [ "${{ inputs.version_bump_type }}" = "rc-major" ] || [ "${{ inputs.version_bump_type }}" = "rc-minor" ] || [ "${{ inputs.version_bump_type }}" = "rc-patch" ] && export PRERELEASE="--prerelease" || export PRERELEASE="--latest"
                    echo "PRERELEASE: $PRERELEASE"
                    echo PRERELEASE=$PRERELEASE >> "$GITHUB_ENV"

              - name: Tag commit and push
                run: |
                  git config --global user.email "bot@github.com"
                  git config --global user.name "github-actions[bot]"
                  git checkout -b branch-v${STEPS_VERSION_OUTPUTS_VERSION}
                  git add -A
                  git commit -m "Bumping version to v${STEPS_VERSION_OUTPUTS_VERSION}"

                  # Tag and push X.X.X
                  git tag -f \
                    -a v${STEPS_VERSION_OUTPUTS_VERSION} \
                    -m "v${STEPS_VERSION_OUTPUTS_VERSION}"
                  git push -f origin "v${STEPS_VERSION_OUTPUTS_VERSION}"

                  # Tag and push X.X
                  git tag -f \
                    -a v${STEPS_VERSION_OUTPUTS_MAJOR}.${STEPS_VERSION_OUTPUTS_MINOR} \
                    -m "v${STEPS_VERSION_OUTPUTS_MAJOR}.${STEPS_VERSION_OUTPUTS_MINOR}"
                  git push -f origin "v${STEPS_VERSION_OUTPUTS_MAJOR}.${STEPS_VERSION_OUTPUTS_MINOR}"

                  # Tag and push X.X.X
                  git tag -f \
                    -a v${STEPS_VERSION_OUTPUTS_MAJOR} \
                    -m "v${STEPS_VERSION_OUTPUTS_MAJOR}"
                  git push -f origin "v${STEPS_VERSION_OUTPUTS_MAJOR}"

                  # Tag and push branch
                  git push -f origin "branch-v${STEPS_VERSION_OUTPUTS_VERSION}"
                env:
                  STEPS_VERSION_OUTPUTS_VERSION: ${{ steps.version.outputs.version }}
                  STEPS_VERSION_OUTPUTS_MAJOR: ${{ steps.version.outputs.major }}
                  STEPS_VERSION_OUTPUTS_MINOR: ${{ steps.version.outputs.minor }}

              - name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
                with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=raw,value=v${{ steps.version.outputs.version }}
                      type=raw,value=v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
                      type=raw,value=v${{ steps.version.outputs.major }}
                      type=raw,value=${{ github.sha }}

              - name: Set up Docker Buildx
                uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

              - name: Log in to the Container registry
                uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
                with:
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}

              - name: Build and push image
                id: push
                uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
                with:
                    build-args: PYTHON_VERSION=${{ steps.setup-python.outputs.python-version }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    context: .
                    load: false
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}

              - name: Build whl
                run: uv build --out-dir dist_pypi

              - name: Publish package distributions to PyPI
                uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # release/v1
                with:
                  packages-dir: dist_pypi/

              - name: Create release
                env:
                    GH_TOKEN: ${{ secrets.PAT_GITHUB }}
                    STEPS_VERSION_OUTPUTS_VERSION: ${{ steps.version.outputs.version }}
                run: |
                    export LAST_RELEASE=$(gh release list --repo ${{ github.repository }} --order desc --json name --limit 1 | jq -r '.[0].name')
                    echo $LAST_RELEASE
                    gh release create v${STEPS_VERSION_OUTPUTS_VERSION} \
                        --generate-notes \
                        --repo ${{ github.repository }} \
                        --notes-start-tag $LAST_RELEASE \
                        --target branch-v${STEPS_VERSION_OUTPUTS_VERSION} \
                        --title 'v${STEPS_VERSION_OUTPUTS_VERSION}' \
                        $PRERELEASE \
                        --verify-tag

              - name: Checkout `gh-pages`
                run: git fetch origin gh-pages --depth=1

              - name: Deploy docs website
                run: |
                  uv run mike deploy --push --update-aliases v${STEPS_VERSION_OUTPUTS_VERSION} stable
                  uv run mike set-default --push stable
                env:
                  STEPS_VERSION_OUTPUTS_VERSION: ${{ steps.version.outputs.version }}
